### ISSUE TITLE
Material theme extension for Zed

### ISSUE THREAD

**Issue by kunaaal13** [material-theme/zed-material-theme#1]
When can we expect to get the material theme extension for Zed.

**Comment by equinusocio** [comment]
If you want to test a basic version, here the folder.

TO install the local extension, from the extension page, click Install Dev extension from the top right, and select the unzipped folder.

![Screenshot 2024-09-19 at 16 06 45](https://github.com/user-attachments/assets/83b405b1-db10-48df-82a7-79a7db756c1e)

[mt.zip](https://github.com/user-attachments/files/17060778/mt.zip)
